sharesound/posts/urls.py
from posts import views
from django.urls import path

urlpatterns = [
    path('sub_post_list.json', views.sub_post_list_json, name="sub_post_list_json"),
    path('', views.subs_track_list, name='sub_posts_list'),
    path('posts/', views.posts_list, name='posts_list'),
    path('post_list.json', views.post_list_json, name="post_list_json"),
    path('posts/<int:post_id>', views.post_detail, name='post_detail'),
    path('genres/', views.genre_list, name='genre_list'),
    path('genres/<int:genre_id>', views.genre_post_list, name='genre_post_list'),
    path('tags/', views.tag_list, name='tag_list'),
    path('tags/<int:tag_id>', views.tag_post_list, name='tag_post_list'),
    path('users/', views.user_list, name='user_list'),
    path('users/<str:username>', views.user_detail, name='user_detail'),
    path('albums/', views.album_list, name='album_list'),
    path('album_list.json', views.album_list_json, name="album_list_json"),
]

sharesound/sharesound/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.urls import include, path
from django.conf.urls.static import static
from sharesound import settings, views
from django.contrib.auth.views import login, logout

urlpatterns = [
    #path('', views.home, name='home'),
    path('admin/', admin.site.urls),
    path('', include('posts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

sharesound/posts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.contrib.contenttypes.fields import GenericForeignKey, GenericRelation
from django.contrib.contenttypes.models import ContentType
from .validators import validate_audiofile_extension, get_valid_audio_extensions
from django.db.models import F
import os

def get_directory(instance, filename):
    ext = os.path.splitext(filename)[1]
    audio_extensions = get_valid_audio_extensions()
    if ext.lower() in audio_extensions:
        directory = 'audio'
    else:
        directory = 'photo'
    try:
        username = instance.created_by.username
    except AttributeError:
        username = instance.username
    return '{0}/{1}/{2}'.format(username, directory, filename)


class User(AbstractUser):
    bio = models.TextField(max_length=500)
    photo = models.ImageField(
        upload_to=get_directory,  #!!!!
        null=True, blank=True
    )
    
    subs = GenericRelation('Sub')

    class Meta(AbstractUser.Meta):
        ordering = ['username']
        indexes = [
            models.Index(fields=['username',]),
            models.Index(fields=['email',]),
            models.Index(fields=['first_name', 'last_name', ]),
        ]


class Album(models.Model):
    title = models.CharField(max_length=100)
    desc = models.TextField()
    cover = models.ImageField(upload_to=get_directory, null=True, blank=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    
    tags = GenericRelation('TagRelationship')
    likes = GenericRelation('Like')
    comments = GenericRelation('Comment')
    
    def __str__(self):
        return self.title
    
    class Meta:
        ordering = ['-created_at']
        indexes = [
            models.Index(fields=['title',]),
            models.Index(fields=['-created_at',]),
            models.Index(fields=['created_by',]),
        ]
    

class Genre(models.Model):
    name = models.CharField(max_length=50)
    
    likes = GenericRelation('Like')
    subs = GenericRelation('Sub')

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']
        indexes = [
            models.Index(fields=['name',]),
        ]

        
class GenreRelationship(models.Model):
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE)
    track = models.ForeignKey('Track', on_delete=models.CASCADE)
    
    def __str__(self):
        return '"{0}" is {1}'.format(self.track.title, self.genre.name)
    
    class Meta:
        ordering = ['genre']
        indexes = [
            models.Index(fields=['genre',]),
            models.Index(fields=['track',]),
        ]


class Tag(models.Model):
    name = models.SlugField(db_index=True)
    
    likes = GenericRelation('Like')
    subs = GenericRelation('Sub')
	
    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']
        indexes = [
            models.Index(fields=['name',]),
        ]

        
class TagRelationship(models.Model):
    tag = models.ForeignKey(Tag, on_delete=models.CASCADE)
    
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')
    
    def __str__(self):
        return '"{0}" was tagged: {1}'.format(self.content_object.__str__(), self.tag.name)
    
    class Meta:
        ordering = ['tag']
        indexes = [
            models.Index(fields=['tag',]),
            models.Index(fields=['content_type', 'object_id',]),
        ]


class Track(models.Model):		
    title = models.CharField(max_length=100)
    desc = models.TextField(help_text='Write a description of the track.')
    genre = models.ManyToManyField(Genre, through=GenreRelationship)
    album = models.ForeignKey(Album, on_delete=models.SET_NULL, blank=True, null=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)
    
    source = models.FileField(upload_to=get_directory, validators=[validate_audiofile_extension])
    picture = models.ImageField(null=True, blank=True, upload_to=get_directory)
    
    created_at = models.DateTimeField(auto_now_add=True)
    
    tags = GenericRelation('TagRelationship')
    likes = GenericRelation('Like')
    comments = GenericRelation('Comment')
	
    def __str__(self):
        return '{0} - "{1}"'.format(self.created_by.username, self.title)

    class Meta:
        ordering = ['-created_at']
        indexes = [
            models.Index(fields=['title',]),
            models.Index(fields=['created_by',]),
            models.Index(fields=['-created_at',]),
        ]


class Comment(models.Model):
    text = models.TextField(max_length=500)
    
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')
    
    created_at = models.DateTimeField(auto_now_add=True)
    
    likes = GenericRelation('Like')

    def __str__(self):
        return self.text[0:50]

    class Meta:
        ordering = ['content_type', 'object_id', '-created_at']
        indexes = [
            models.Index(fields=['content_type', 'object_id' , '-created_at',]),
        ]
        

class Like(models.Model):
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')

    def __str__(self):
        return '{0} liked {1}: "{2}"'.format(self.created_by.username, self.content_type.model, self.content_object.__str__()) 
	
    class Meta:
        ordering = ['content_type', 'object_id']
        indexes = [
            models.Index(fields=['content_type', 'object_id'],),
            models.Index(fields=['created_by', '-created_at',]),
        ]        
        

class Sub(models.Model):
    from_user = models.ForeignKey(User, on_delete=models.CASCADE)
    
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')
	
    def __str__(self):
        return '{0} subscribed to {1}: {2}'.format(self.from_user.username, self.content_type, self.content_object.__str__())
	
    class Meta:
        ordering = ['from_user']
        indexes = [
            models.Index(fields=['from_user',]),
            models.Index(fields=['content_type', 'object_id',]),
        ]

sharesound/posts/templates/posts/album_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Список альбомов
{% endblock %}

{% block content %}  
    <div id="root"></div>
    
    <script src="{% static 'js/album_list.bundle.js' %}"></script>
{% endblock %}

sharesound/posts/templates/posts/genre_list.html
{% extends 'base.html' %}

{% block content %}
    <ul class="list-group list-group-flush">
        {% for genre in genre_list %}
            <li class="list-group-item list-group-item-action text-center" onClick='location.href="{% url 'genre_post_list' genre.id %}"'>
                <a href="{% url 'genre_post_list' genre.id %}">{{ genre.name }}</a>
                <div class="">
                    <span title="Количество подписчиков"><span class="oi oi-person mx-2"></span>{{ genre.subs.count }}</span>
                    <span title="Количество треков"><span class="oi oi-audio-spectrum mr-2 ml-4"></span>{{ genre.track_set.count }}</span>
                    <span title="Количество лайков"><span class="oi oi-heart mr-2 ml-4 my-3"></span>{{  genre.likes.count }}</span>                
                </div>
            </li>
        {% endfor %}
    </ul>
{% endblock %}

sharesound/posts/templates/posts/post_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}{{ post.created_by.username }} - {{ post.title }} {% endblock %}

{% block content %}
    
    <h1 class="display-4">{{ post.title }}</h1>
    <hr class="mb-1">
    <div class="float-right text-muted">{{ post.created_at }}</div>   
    <div class="float-left">
        {% for tagrel in post.tags.select_related %}              
            <span class="badge badge-secondary">{{ tagrel.tag.name }}</span>
        {% empty %}
            <span class="badge badge-secondary">Нет тегов</span>
        {% endfor %}  
    </div>
    <br>
    <div class="row">
        <div class="col-12 col-md-6 col-xl-6 text-center">
            <img class="img-fluid img-thumbnail align-self-center"   src={% if post.picture %}
                                                                "{{ post.picture.url }}"
                                                            {% else %}
                                                                "{% static 'img/empty_cover.png' %}"
                                                            {% endif %} />
        </div>
        <div class="col-12 col-md-6 col-xl-6">
            <div class="my-5 bg-light text-center">
                <audio controls src="{{ post.source.url }}"></audio>
            </div>
            <div>
                <h5>
                    <span class="text-muted">Исполнитель:</span> 
                    <a href="{% url 'user_detail' post.created_by.username %}">
                        {% if post.created_by.photo %}
                            <img class="rounded-circle ml-3" width="50" height="50" src="{{ post.created_by.photo.url }}">
                        {% endif %}
                        {{ post.created_by.username }}
                    </a>
                </h5>
                {% if post.album is not None %}
                    <h5>
                        <span class="text-muted">Альбом:</span>
                        <a href="">"{{ post.album.title }}"</a>
                    </h5>
                {% endif %}
                <h5>
                    <span class="text-muted">Жанры:</span>
                    {% for g in post.genre.select_related %}
                        <a class="none-decor-hover" href="{% url 'genre_post_list' g.id %}">
                            <span class="badge badge-info">
                                {{ g.name }}
                            </span>
                        </a>
                    {% endfor %}
                </h5>
                <div>
                    <span class="oi oi-heart mx-2 my-3" title="Likes" aria-hidden="true"></span>{{  post.likes.count }}
                    <span class="oi oi-comment-square ml-4 mr-2" title="Comments"></span>{{  post.comments.count }}
                </div>
            </div>
        </div>
    </div>                                    
    <p class="lead my-3"> {{ post.desc }} </p>
    <hr>
    <h2>Комментарии:</h2>
    {% for comment in comments %}
        <div class="card border-info mb-4">
            <div class="card-header">
                <a class="none-decor-hover" href="{% url 'user_detail' comment.created_by.username %}">
                    {{ comment.created_by.username }}
                </a>
                <span class="text-muted">оставил комментарий:</span>
            </div>
            <div class="card-body text-info">
                {{ comment.text }}
                <div class="text-right">
                    {{ comment.likes.count }}
                    <span class="oi oi-heart mx-2 my-3" title="Likes" aria-hidden="true"></span>
                </div>
            </div>
        </div>
    {% empty %}
        Нет комментариев        
    {% endfor %}
    
{% endblock %}

sharesound/posts/templates/posts/posts_list.html
{% extends "base.html" %}
{% load static %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
    <div id="root">
    </div>
    
    <script src="{% static 'js/post_list.bundle.js' %}"></script>
{% endblock %}

sharesound/posts/templates/posts/sub_posts_list.html
{% extends "base.html" %}
{% load static %}

{% block title %}Лента{% endblock %} 

{% block content %}    
    <div id="root">
    </div>
    
    <script src="{% static 'js/sub_post.bundle.js' %}"></script>
{% endblock %}

sharesound/posts/templates/posts/subs_list.html
{% extends 'base.html' %}

{% block title %}Лента{% endblock %}

{% block nav_sub_posts %}active{% endblock %}

{% block content %}
    {% for post in posts %}
        <div>
            <h3>{{ post.title }}</h3>
            <h5>
                {{ post.created_by }}            
                {{ post.created_at }}
            </h5>
        </div>
    {% endfor %}
{% endblock %}

sharesound/posts/templates/posts/tag_list.html
{% extends 'base.html' %}

{% block content %}
    {% for tag in tag_list %}
        <div>
            <a href="{% url 'tag_post_list' tag.id %}">{{ tag.name }}</a>
        </div>
    {% endfor %}
{% endblock %}

sharesound/posts/templates/posts/user_detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Пользователь '{{ user.username }}'{% endblock %}

{% block content %}
    <h1 class="display-4">{{ user.username }} - {{ user.get_full_name }}</h1>
    <hr>
    <div class="row">
        <div class="col-12 col-md-6">
            <img class="img-fluid img-thumbnail align-self-center"   src={% if user.photo %}
                                                                            "{{ user.photo.url }}"
                                                                        {% else %}
                                                                            "{% static 'img/empty_cover.png' %}"
                                                                        {% endif %} />
        </div>
        <div class="col-12 col-md-6">
            <div class="card my-5">
                <div class="card-header">
                    <h5>Биография:</h5>
                </div>
                <div class="card-body">
                    <p>{{ user.bio }}</p>
                </div>
            </div>
            <div class="row text-center">
                <div class="col">
                    <h4>Подписчиков:</h4>
                    <strong>{{ user.subs.count }}</strong>
                </div>
                <div class="col">
                    <h4>Подписок:</h4>
                    <strong>{{ user.sub_set.count }}</strong>
                </div>
                <div class="col">
                    <h4>Треков:</h4>
                    <strong>{{ user.track_set.count }}</strong>
                </div>
            </div>
        </div>
    </div>  
        
{% endblock %}

sharesound/posts/templates/posts/user_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Список пользователей{% endblock %}

{% block content %}
    <div class="jumbotron">
        <form class="container-fluid" method='get'>
            <h2>Фильтрация:</h2>
            <hr>
            <div class="row">
                <div class="col-12 col-md-6 form-group">
                    <label for='username_search'>Username:</label>
                    <input class="form-control" id='username_search' name='username' value="{{ search_dict.username }}" type='text' />
                </div>
                <div class="col-12 col-md-6 form-group">     
                    <label for="name_search">Имя:</label>
                    <input class="form-control" id='name_search' name='name' value="{{ search_dict.name }}" type='text' />
                </div>
            </div>
            <input class="btn btn-primary" type='submit' value='Поиск'/>
        </form>
    </div>
    <ul class="list-group list-group-flush">
        {% for user in user_list %}
            <li class="list-group-item">
                <img class="rounded-circle mr-3" width='50' height='50' src="{% if user.photo %}
                                                                            {{ user.photo.url }}
                                                                        {% else %}
                                                                            {% static 'img/empty_cover.png' %}
                                                                        {% endif %}" />
                <span class="h5"><a href="{% url 'user_detail' user.username %}">
                    {{ user.username }}
                </a></span>
                <span class="text-muted"> - {{ user.get_full_name }}:</span>
                <span class="mx-5 lead">{{ user.bio|truncatewords:5 }}</span>
                <div class="float-right allign-self-center">
                    <span title="Количество подписчиков"><span class="oi oi-person mx-2"></span>{{ user.subs.count }}</span>
                    <span title="Количество треков"><span class="oi oi-audio-spectrum mr-2 ml-4"></span>{{ user.track_set.count }}</span>
                </div>
            </li>
        {% endfor %}
    </ul>
{% endblock %}